name: Update README content feeds
on:
  schedule:
    - cron: '0 9 * * *'   # daily at 9am UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update articles
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "ARTICLES"
          feed_list: "https://dev.to/feed/drjoanneskiles,https://chaotictoejam.substack.com/feed"
          max_post_count: "5"
          template: "$newline- [$title]($url)$newline"

      - name: Update videos
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "VIDEOS"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC0fsRDyOi52N3GeInLIz6lA"
          max_post_count: "5"
          template: "$newline- [$title]($url)$newline"

      - name: Update podcasts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "PODCASTS"
          feed_list: "https://anchor.fm/s/1117b1134/podcast/rss,https://anchor.fm/s/10e91d00c/podcast/rss"
          max_post_count: "5"
          template: "$newline- [$title]($url)$newline"
